Bank-Of-Chain/boc-web

src/components/ApproveArray/index.jsx, src/components/ApproveArray/style.js, src/index.css
add loading to approve and swap button
=> fix: add loading to approve and swap button

src/components/ApproveArray/index.jsx
=> fix: update logic

src/App.css, src/__tests__/components/Footer/__snapshots__/Footer.test.js.snap, src/components/Footer/Footer.jsx, src/components/Footer/footerStyle.js, src/components/Header/headerStyle.js, src/index.css, src/pages/Home/components/RoadMapSectionV2.jsx, src/pages/Home/components/lendingStyle.js, src/pages/Home/components/roadMapV2Style.js, src/pages/InvestNew/Withdraw/index.jsx, src/pages/InvestNew/index.jsx
=> fix: update text and style

src/components/Header/HeaderLinks.jsx, src/helpers/location.js
=> chore: host url switch automatic

src/pages/Home/components/LendingSection.jsx
1. LendSection displayed with one max value 
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewwAiWF2K&record=recvERGT5d&field=fldXv6F1uI
=> fix: display LendSection with one max value

src/components/Header/HeaderLinks.jsx
=> chore: value update

src/pages/Home/components/LendingSection.jsx
=> fix: staking

src/components/Header/HeaderLinks.jsx, src/pages/Home/components/LendingSection.jsx
=> code merge

src/__tests__/pages/Home/components/AmmSection/__snapshots__/AmmSection.test.js.snap, src/constants/amms.js, src/pages/Home/components/AmmSection.jsx
1. aura path fixed
2. text update
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recJdpk7AG&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=recVSIbtH4&field=fldSMld39s
=> chore: aura path fixed

src/constants/amms.js
1. url update
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recxbcDJoX&field=fldXv6F1uI
=> chore: link update

src/components/Card/index.jsx, src/components/MyStatement/index.jsx, src/constants/amms.js, src/pages/Ethi/index.jsx, src/pages/Home/components/LendingSection.jsx
1. bug fixed
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recqhfRPQk&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=rechAuOYYJ&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recDmUiKYp&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recxbcDJoX&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recm3oQ6eW&field=fldXv6F1uI
=> fix: my statement page bug fixed

src/components/MyStatement/index.jsx, src/pages/Ethi/index.jsx, src/pages/InvestNew/index.jsx
=> refactor: code update

.github/workflows/release.yml, package.json, src/components/Echarts/bar/index.js, src/components/Echarts/line/index.js, src/components/Echarts/pie/index.js, src/components/Footer/Footer.jsx, src/components/Header/HeaderLinks.jsx, src/components/MyStatement/MyStatement1.jsx, src/components/MyStatement/index.jsx, src/helpers/swap-util.js, src/hooks/usePersonalData.js, src/hooks/useRedeemFeeBps.js, src/hooks/useVault.js, src/pages/Ethi/Deposit/index.jsx, src/pages/Ethi/Withdraw/index.jsx, src/pages/Ethi/index.jsx, src/pages/Ethr/Deposit/index.jsx, src/pages/Ethr/Withdraw/index.jsx, src/pages/Ethr/index.jsx, src/pages/InvestNew/Deposit/index.jsx, src/pages/InvestNew/Withdraw/index.jsx, src/pages/InvestNew/index.jsx, src/pages/Usdr/Deposit/index.jsx, src/pages/Usdr/Withdraw/index.jsx, src/pages/Usdr/index.jsx
=> refactor: text update

src/__tests__/pages/Home/components/AmmSection/__snapshots__/AmmSection.test.js.snap
=> test: snapshot update

configs/config.template.js, src/App.jsx, src/components/Frame/style.js, src/components/Header/HeaderLinks.jsx, src/components/VaultChange/index.jsx, src/components/VaultChange/style.js, src/config/config.js, src/pages/Ethi/index.jsx, src/pages/Ethi/style.js, src/pages/Ethr/index.jsx, src/pages/Ethr/style.js, src/pages/Home/index.jsx, src/pages/InvestNew/index.jsx, src/pages/InvestNew/style.js, src/pages/Usdr/index.jsx, src/pages/Usdr/style.js
=> feat: VaultChange

src/components/MyVault/index.jsx, src/components/VaultChange/index.jsx, src/hooks/useVaultFactory.js, src/pages/Usdr/Deposit/index.jsx, src/pages/Usdr/Deposit/style.js, src/pages/Usdr/Withdraw/index.jsx, src/pages/Usdr/Withdraw/style.js, src/pages/Usdr/index.jsx, src/pages/Usdr/style.js
=> feature: switch vault logics upgrade

src/App.jsx, src/components/VaultChange/index.jsx, src/constants/index.js
1. chain change logic add in Component VaultChange
=> feature: add chain change logic in Component VaultChange

src/abis/common/uniswapv3-risk-on-vault.json
=> feat: update abi

src/components/Echarts/options/line/getLineEchartOpt.js, src/components/MyStatement/MyStatementForRiskOn.jsx, src/components/MyStatement/index.jsx, src/components/MyVaultPage/index.jsx, src/pages/Ethr/index.jsx, src/pages/Ethr/style.js, src/pages/Usdr/index.jsx
1. bug fixed
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=rec1CcTfwx&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=rech5P7pbG&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recXtHNXGZ&field=fldXv6F1uI
=> refactor: code udpate

src/hooks/useVaultOnRisk.js, src/pages/Ethr/Deposit/index.jsx, src/pages/Ethr/Deposit/style.js, src/pages/Ethr/Withdraw/index.jsx, src/pages/Ethr/index.jsx, src/pages/Usdr/Deposit/index.jsx, src/pages/Usdr/Deposit/style.js, src/pages/Usdr/Withdraw/index.jsx, src/pages/Usdr/index.jsx
=> feat: min investment

src/components/MyStatement/MyStatementForRiskOn.jsx, src/pages/Ethr/Deposit/index.jsx, src/pages/Ethr/index.jsx, src/pages/Usdr/Deposit/index.jsx, src/pages/Usdr/index.jsx
=> fix: handle deposit success

src/components/MyStatement/MyStatementForRiskOn.jsx
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recZ41mNsl&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recUY9AeL2&field=fldXv6F1uI
=> fix: use lastItem as current profits

src/components/MyStatement/MyStatementForRiskOn.jsx, src/pages/Ethr/Deposit/index.jsx, src/pages/Ethr/Withdraw/index.jsx, src/pages/Ethr/index.jsx, src/pages/Usdr/Deposit/index.jsx, src/pages/Usdr/Withdraw/index.jsx, src/pages/Usdr/index.jsx
=> fix: on withdraw success

src/components/CustomTabs/CustomTabs.jsx, src/components/VaultChange/index.jsx, src/components/VaultChange/style.js
1.  vaultchange component style update
=> style: vaultchange component style update

.github/workflows/release.yml
=> chore: node

src/components/Header/HeaderLinks.jsx
1. bridge url upgrade
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=recyggH5v9&field=fldSMld39s
=> chore: bridge url changed

src/components/MyStatement/MyStatementForRiskOn.jsx, src/hooks/useVaultOnRisk.js, src/pages/Ethr/index.jsx, src/pages/Usdr/index.jsx
=> feat: liquidation line

src/__tests__/pages/Home/components/AmmSection/__snapshots__/AmmSection.test.js.snap, src/components/CustomTabs/CustomTabs.jsx, src/components/CustomTabs/customTabsStyle.js, src/components/VaultChange/index.jsx
=> fix: update tab layout, style

src/components/VaultChange/index.jsx, src/components/VaultChange/style.js
1. products list
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=recvb981aL&field=fldSMld39s
=> feature: products list optimation

configs/config.template.js, src/App.jsx, src/components/Header/HeaderLinks.jsx, src/config/config.js, src/pages/Home/index.jsx
=> feat: router usdi

src/components/CustomTextField/index.jsx, src/components/CustomTextField/style.js, src/pages/InvestNew/Deposit/index.jsx
1. CustomTextField component style upgrade
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=recrXuFvmy&field=fldSMld39s
=> styles: CustomTextField component style upgrade

src/pages/Ethi/style.js, src/pages/InvestNew/style.js
=> styles: hover styles add

src/components/Card/index.jsx, src/components/Header/HeaderLinks.jsx, src/components/Header/headerLinksStyle.js, src/components/MyStatement/index.jsx, src/components/MyStatement/style.js, src/pages/Ethi/index.jsx, src/pages/InvestNew/index.jsx
=> style: My Account Card

src/components/Header/Header.jsx, src/components/Header/headerStyle.js, src/pages/Home/components/AmmSection/ammStyle.js, src/pages/Home/index.jsx
=> style: logo

src/helpers/error-handler.js, src/pages/Ethi/Deposit/index.jsx, src/pages/InvestNew/Deposit/index.jsx
=> refactor: logics update for error catch

src/pages/Ethi/Deposit/index.jsx, src/pages/InvestNew/Deposit/index.jsx
=> fix: apy period update

src/pages/Home/index.jsx
1. number formate fixed
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recC6sONMm&table=tblS8STLMSlS4f8a&view=vewoKchwWv
=> fix: numeral format change for a huge tvl number

src/__tests__/components/Footer/__snapshots__/Footer.test.js.snap, src/components/Footer/Footer.jsx, src/config/config.js
1. url upgrade
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recMZFc8EO&table=tblS8STLMSlS4f8a&view=vewoKchwWv
=> chore: docs link url upgrade

configs/config.template.js
1. template update
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recMZFc8EO&table=tblS8STLMSlS4f8a&view=vewoKchwWv
=> chore: template update

src/__tests__/components/Footer/__snapshots__/Footer.test.js.snap, src/components/Footer/Footer.jsx, src/config/config.js
Reverts Bank-Of-Chain/boc-web#233
=> Revert "chore: docs link url upgrade"

configs/config.template.js
Reverts Bank-Of-Chain/boc-web#234
=> Revert "chore: template update"

src/pages/Home/components/LendingSectionV2/lendingStyle.js
1. padding update
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=rec51OyMCh&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
=> styles: padding update

src/services/subgraph-service.js
Fix Deposit page get APY error
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=rec9pgDi65&table=tblS8STLMSlS4f8a&view=vewwAiWF2K
=> fix: get apy

src/pages/Ethi/Deposit/index.jsx, src/pages/InvestNew/Deposit/index.jsx
1. tvl cards removed
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=reclTZFjis&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
=> fix: remove cards in deposit page

.github/workflows/demo1.yml, .github/workflows/testcases.yml, .github/workflows/vars.yml
=> testing pr

src/__tests__/components/Footer/__snapshots__/Footer.test.js.snap, src/__tests__/constants/invest.test.js, src/__tests__/pages/Home/components/LendingSection/__snapshots__/LendingSection.test.js.snap, src/pages/Ethi/LeverBoard/index.jsx, src/pages/Home/components/LendingSection/index.jsx
1. personal apy fetching logics fixed
1. https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recmVdovq1&table=tblS8STLMSlS4f8a&view=vewoKchwWv
=> fix: personal apy fetching logics fixed

src/pages/Team/style.js
1. styles adapter
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recqF8zli2&table=tblS8STLMSlS4f8a&view=vewoKchwWv
=> styles: styles update in mobile

src/pages/Ethi/Withdraw/index.jsx, src/pages/InvestNew/Withdraw/index.jsx
1. add logics on withdraw call for error rltm catching
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recxTzUvbX&table=tblS8STLMSlS4f8a&view=vewoKchwWv
=> fix: add rltm catching on withdraw call

src/pages/Ethi/Deposit/index.jsx, src/pages/Ethi/Withdraw/index.jsx, src/pages/InvestNew/Deposit/index.jsx, src/pages/InvestNew/Withdraw/index.jsx
1. error text update
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=rec4DeDIW3&table=tblS8STLMSlS4f8a&view=vewoKchwWv
=> fix: error text update

src/components/SnackBarCard/index.jsx
1. add close icon in SnackBarCard
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=recXKg4aEO&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
=> feature: close icon add in SnackBarCard

src/abis/v2.0/vault-abi.json, src/components/SnackBarCard/index.jsx, src/components/Tabs/index.jsx, src/hooks/useVault.js, src/pages/Ethi/Deposit/index.jsx, src/pages/Ethi/Withdraw/index.jsx, src/pages/InvestNew/Deposit/index.jsx, src/pages/InvestNew/Withdraw/index.jsx, src/pages/Pools/components/Info/EthiInfo.jsx, src/pages/Pools/components/Info/UsdiInfo.jsx, src/pages/Pools/index.jsx
1. "pendding" text fixed
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=reciSfWQmx&table=tblS8STLMSlS4f8a&view=vewoKchwWv
=> fix: text update

src/pages/Home/components/LendingSectionV2/index.jsx, src/pages/Home/components/LendingSectionV2/lendingStyle.js
1. notices add in home page
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=recVcMHdGz&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
=> feature: notices add in home page

src/components/Header/Header.jsx
1. add beta text
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=recdmUEAAc&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
=> feature: add beta text beside logo

src/components/Header/HeaderLinks.jsx
1. add btn link to v1 homepage
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=rec24sQT4Y&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
=> feature: add btn link to legacy version

src/components/Header/HeaderLinks.jsx
1. add btn link to v2 homepage
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=rec24sQT4Y&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
=> feature: add btn link to v2 version
